services:
  - type: web
    name: queens-pub-kviz
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST_KEY
        sync: false
